global using System.Reflection;
global using Blogi.Domain.Entities;
global using Blogi.Persistence.Contexts;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.Extensions.Configuration;
global using Core.Persistence.Repositories.Abstracts;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.EntityFrameworkCore.Metadata.Builders;
global using Blogi.Application.Repositories.LanguageRepository;
